# See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: 👒 Dependency updates
      labels:
        - bump-from/vendir
    - title: Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - bump-from/vendir
