apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.34.0
directories:
# doc: https://carvel.dev/vendir/docs/v0.35.x/vendir-spec/

- path: src/github.com
  contents:

  # validates checksums automatically from release notes
  - path: kubernetes/kubectl
    githubRelease:
      slug: kubernetes/kubernetes
      tag: v1.27.0
      disableAutoChecksumValidation: true
      http:
        # The url parameter of http can interpolate the tag of the GitHub release using the {tag} token.
        url: https://dl.k8s.io/release/{tag}/bin/linux/amd64/kubectl
    permission: 0755

  - path: k3s-io/k3s
    githubRelease:
      slug: k3s-io/k3s
      tag: v1.27.0
      disableAutoChecksumValidation: true
      assetNames: # only download specific assets (optional; v0.12.0+). We use assetNames inside githubRelease instead of
      # includePaths at path level. Using includePaths downloads all assets and filter after.
      - "k3s"
      - "k3s-airgap-images-amd64.tar"
    # includePaths: # includes paths specify what should be included. by default all paths are included (optional)

