name: create-release-branches

permissions:
  contents: write # allow git push to repo and the github release and its artefact

on:
  workflow_call:
    inputs:
      force_push:
        description: 'Force recreation of release branches from min version'
        required: true
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      force_push:
        description: 'Force recreation of release branches from min version'
        required: true
        type: boolean
        default: false
  schedule:
    - cron: "30 10 * * 1" # “At 10:30 on Monday.” https://crontab.guru/#30_10_*_*_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      # GH cli is already pre-install, see https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows

      - name: Install yq cli
        #See https://github.com/marketplace/actions/install-a-binary-from-github-releases
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: mikefarah/yq
          tag: v4.48.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # reduce potential rate limiting

      - name: create-missing-branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_PUSH: ${{ inputs.force_push}}
        run: |
          # configure git
          git config --global user.name "workflows/k3s-boshrelease/create-release-branches"
          git config --global user.email "<>"
          git config --global --add safe.directory /github/workspace
          ./create-release-branches.bash

